FROM golang:1.18-alpine

# Set the working directory
WORKDIR /app

RUN apk update && apk add --no-cache git


COPY src/go.mod src/go.sum ./

RUN go mod download



# Install air for hot-reloading
RUN go install github.com/cosmtrek/air@v1.42.0


COPY src .


EXPOSE 3000


CMD ["/go/bin/air", "-c", "src/air.toml"]